version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - errname
    - errorlint
    - gocyclo
    - gosec
    - misspell
    - nilerr
    - nilnil
    - prealloc
    - revive
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - all
        path: generated_.*\.go
      - linters:
          - gosec
        text: 'G404:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
