# .goreleaser.yml

before:
  hooks:
    - ./set-version.sh

builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goarch: "386"
        goos: darwin
archives:
  - format_overrides:
      - goos: windows
        format: zip

brews:
  - name: stevedore

    tap:
      owner: JamesWoolfenden
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"


    commit_author:
      name: "GitHub Action"
      email: action@github.com

    homepage: "https://github.com/JamesWoolfenden/stevedore#readme"

    description: "stevedore is a tool for managing Dockerfile labels"

    install: |
      bin.install "stevedore"

    test: |
      system "#{bin}/stevedore", "--help"
